					<p class="image-holder">
						<img src="images/ph_history.jpg" class="fp_ph" alt=""/>
						<span class="caption">Main House</span>
					</p>

					<p>This house, built in 1861, was the home of Frank Lloyd Wright's uncle James Lloyd-Jones. Wright spent boyhood summers here, working on his uncle's farm and falling in love with the valley where he would later build his own home. It's said that from the upper front window of the house, young Wright could see the sites of Taliesin, the masterpiece he built for himself; Unity Chapel, whose ceiling represents his first work as an architect; and Hillside School, which he designed for his aunts and later made the headquarters of his architectural fellowship. Taliesin and the school, obscured by trees, are no longer visible from the Main House at Aldebaran but can be seen from other parts of the property. Still clearly visible from the Main House are the chapel; Taliesin's twin-tower windmill, called Romeo &amp; Juliet; and the Midway Barns, which lie halfway between the school and Taliesin.</p>
					<p>In the 1960s the James Lloyd-Jones property was purchased and renovated by the architect William Wesley Peters, Wright's associate and son-in-law. Peters, who considered himself an acolyte of the great man, named the farm Aldebaran, which is Arabic for "the follower" and the name of a bright red star in the eye of the constellation Taurus.</p>
					<p>The property, which comprises several buildings and about 18 acres, was later owned by Robert and Derry Graves, who sold it to the present owners in 2003. Robert and Derry had a hand in many Spring Green community enterprises, including the Gard Theatre, the American Players Theatre, and the Wyoming Valley School. Until his death in 2011, Robert, who was a landscape architect for Wright in the late 1950s, tended to the valley lovingly and worked to protect its beauty.</p>
			<p class="caption">Publicity rights to Frank Lloyd Wright's name belong to the Frank Lloyd Wright Foundation, Scottsdale, AZ. Used with permission.</p>
