					<p class="image-holder">
						<img src="images/taliesin.jpg" class="fp_ph" alt="" />
						<span class="caption">Front porch view</span>
					</p>

					<p>Aldebaran Farm is located in the "driftless," or unglaciated, region of south-central Wisconsin, an area of rolling hills and valleys and picturesque farms. It's just south of the village of <a href="http://www.springgreen.com/" target="_blank">Spring Green</a>, walking distance from <a href= "http://www.taliesinpreservation.org" target="_blank">Taliesin</a> and the Frank Lloyd Wright Visitors Center, and minutes from the Wisconsin River, <a href= "http://americanplayers.org/" target="_blank">American Players Theatre</a>, and <a href="http://www.stateparks.com/tower_hill.html" target="_blank">Tower Hill State Park</a>. Recreational opportunities include the <a href= "http://www.thehouseontherock.com/HOTR_Golf_CourseInfo.htm" target= "_blank">Springs</a> Golf Course, designed by Robert Trent Jones, <a href= "http://www.wiriverside.com/" target="_blank">canoeing</a> on the river, and walking, <a href="http://www.travelwisconsin.com/things-to-do/outdoor-fun/natural-attractions-parks/trails-hiking/directory" target= "_blank">hiking</a>, and <a href= "http://www.cyclesouthwestwisconsin.com/index.php" target= "_blank">biking</a> through the glorious countryside that inspired America's greatest architect. "After a while," Wright told his sister Maginel, "the valley taught me everything."</p>

					<p class="image-holder">
						<iframe class="fp_ph" width="470" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps/ms?f=q&amp;hl=en&amp;ie=UTF8&amp;msa=0&amp;msid=107733009544102510734.00043c10e909d50d5456c&amp;om=1&amp;source=embed&amp;ll=43.133061,-90.065918&amp;spn=5.611952,9.338379&amp;z=6&amp;output=embed"></iframe>
						<span class="caption"><a href="http://maps.google.com/maps/ms?f=q&amp;hl=en&amp;ie=UTF8&amp;msa=0&amp;msid=107733009544102510734.00043c10e909d50d5456c&amp;om=1&amp;source=embed&amp;ll=43.133061,-90.065918&amp;spn=5.611952,9.338379&amp;z=6">Click</a> for details and directions. Zoom in to see nearby attractions and stores.</span>
					</p>
